export type RegistrationFileItem = {
  id: string;
  registrationId: string;
  fileName: string;
  mimeType: string;
  fileSize: number;
  fileCategory: string;
  uploadedAt: string;
};

export type AuditTrailItem = {
  id: string;
  registrationId: string;
  action: string;
  description: string;
  performedBy: string | null;
  createdAt: string;
};

export type Registration = {
  id: string;
  trackingNumber: string;
  customerName: string;
  mobile: string;
  email: string | null;
  address: string | null;
  country: string | null;
  state: string | null;
  city: string | null;
  customerType: string | null;
  documentType: string | null;
  documentIssuedCountry: string | null;
  processType: string | null;
  subPackage: string | null;
  externalProcess: string | null;
  priority: string | null;
  committedDuration: string | null;
  deliveryLocation: string | null;
  totalCharges: number;
  advancePaid: number;
  balanceAmount: number;
  paymentMode: string | null;
  upiTransactionId?: string | null;
  bankName?: string | null;
  transactionRefNo?: string | null;
  transferDate?: string | null;
  chequeNumber?: string | null;
  chequeDate?: string | null;
  ddNumber?: string | null;
  ddDate?: string | null;
  cardLast4?: string | null;
  approvalCode?: string | null;
  paymentGateway?: string | null;
  onlineTransactionId?: string | null;
  walletName?: string | null;
  walletTransactionId?: string | null;
  paymentReferenceNo?: string | null;
  paymentDescription?: string | null;
  paymentStatus: string;
  collectedPerson: string | null;
  commissionToUserId: string | null;
  commissionToName: string | null;
  commissionToEmail: string | null;
  registeredPerson: string | null;
  regionOfRegistration: string | null;
  bmStatus: string;
  acceptedBy: string | null;
  acceptedAt: string | null;
  approvalStatus: string;
  advancePaymentStatus?: string;
  advancePaymentRejectionReason?: string | null;
  advancePaymentApprovedBy?: string | null;
  advancePaymentApprovedAt?: Date | string | null;
  advancePaymentRejectedBy?: string | null;
  advancePaymentRejectedAt?: Date | string | null;
  trackingStatus: string;
  welcomeCallStatus: string;
  welcomeCalledBy: string | null;
  welcomeCalledAt: string | null;
  leadId?: string | null;
  corporateDetailId?: string | null;
  corporateDetail?: { id: string; companyName: string; contactPersonName: string; contactPersonMobile: string } | null;
  ownerAdminId?: string | null;
  createdBy?: { id: string; name: string | null; email: string | null } | null;
  createdById?: string | null;
  createdAt: string;
  updatedAt: string;
  createdDate: string;
  files: RegistrationFileItem[];
  auditTrail: AuditTrailItem[];
};

export type RegistrationFormState = {
  trackingNumber: string;
  customerName: string;
  mobile: string;
  email: string;
  address: string;
  country: string;
  state: string;
  city: string;
  customerType: string;
  corporateDetailId?: string;
  documentType: string;
  documentIssuedCountry: string;
  processType: string;
  subPackage: string;
  externalProcess: string;
  priority: string;
  committedDuration: string;
  deliveryLocation: string;
  totalCharges: string;
  advancePaid: string;
  paymentMode: string;
  upiTransactionId?: string;
  bankName?: string;
  transactionRefNo?: string;
  transferDate?: string;
  chequeNumber?: string;
  chequeDate?: string;
  ddNumber?: string;
  ddDate?: string;
  cardLast4?: string;
  approvalCode?: string;
  paymentGateway?: string;
  onlineTransactionId?: string;
  walletName?: string;
  walletTransactionId?: string;
  paymentReferenceNo?: string;
  paymentDescription?: string;
  paymentStatus: string;
  collectedPerson: string;
  commissionToUserId: string;
  commissionToName: string;
  commissionToEmail: string;
  registeredPerson: string;
  regionOfRegistration: string;
  approvalStatus: string;
  trackingStatus: string;
  leadId?: string;
};
