export const processTypesMasterList = [
  "UAE Embassy & MOFA",
  "UAE MOFA Only",
  "UAE Consulate",
  "UAE Embassy & MOFA & Translation",
  "Only UAE Embassy & MOFA",
  "Oman Embassy",
  "Saudi Consulate",
  "Qatar Consulate",
  "Qatar Embassy Only",
  "Qatar Embassy & MOFA",
  "Qatar Embassy & MOFA & Translation",
  "Kuwait Consulate",
  "Kuwait Embassy",
  "Kuwait Embassy & Translation",
  "Saudi Culture",
  "Saudi Culture + Apostille with Barcode",
  "China Consulate",
  "China Embassy Attestation",
  "Translation",
  "Sworn Translation",
  "Apostille with Barcode",
  "Apostille with WNR",
  "Apostille - Not Verified",
  "HRD + Apostille (Italy)",
  "HRD + Apostille (Taiwan)",
  "Vietnam Attestation",
  "Egypt Attestation",
  "Malaysia Attestation",
  "Ethiopia Attestation",
  "Thailand Attestation",
  "Philippines Attestation",
  "Taiwan Attestation",
  "Indonesia Attestation",
  "Zimbabwe Attestation",
  "Andhra Pradesh HRD",
  "Assam (Guwahati) HRD",
  "Chhattisgarh - Raipur HRD",
  "Delhi HRD",
  "Goa HRD",
  "Gujarat HRD",
  "Haryana HRD",
  "Karnataka HRD",
  "Kerala HRD",
  "Madhya Pradesh HRD",
  "Maharashtra HRD",
  "Odisha HRD",
  "Punjab HRD",
  "Sikkim HRD",
  "Tamil Nadu HRD",
  "Uttar Pradesh HRD",
  "West Bengal HRD",
  "Bihar HRD",
  "Jharkhand - Ranchi HRD",
  "Uttarakhand HRD",
  "State Home Department (Non-Educational Documents)",
  "Mumbai Notary + Home Department",
  "Only MEA",
  "UAE Police Clearance Certificate",
  "Kuwait Police Clearance Certificate",
  "Oman Police Clearance Certificate",
  "Saudi Police Clearance Certificate",
  "Qatar Police Clearance Certificate",
  "WES Attestation",
  "Kuwait Visa Stamping",
  "Other Services (Arrangement of Documents)",
];
